[package]
build_opts = []
deps = []

[distribution]
build_opts = []
pack_extras = ["templates"]
cross_targets = [["linux", "amd64"]]

[assets]
url_prefix = "/assets"
assets_mapping_pkg = "main"
image_exts = [".png", ".jpg", ".jpeg", ".gif"]
deps = [
    "lodash@3.6.0",
    "color@0.10.1",
    "utf-8-validate@1.2.1",
    "bufferutil@1.3.0",
    "websocket@1.0.23",
    "uglifyify@3.0.4",
    "browserify@13.3.0",
    "envify@4.0.0",
    "babelify@7.3.0",
    "babel-preset-es2015@6.18.0",
    "nib@1.1.2",
    "stylus@0.54.5",
    "coffeeify@2.1.0",
]

[[assets.entry]]
name = "archon"
